version: "3"
services:
  localstack:
    image: localstack/localstack:0.14.0
    networks:
      - hmpps
    container_name: hpfnm-local-localstack
    ports:
      - "4566-4597:4566-4597"
    environment:
      - SERVICES=sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
      - PORT_WEB_UI=${PORT_WEB_UI- }
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  migration-db:
    image: postgres
    networks:
      - hmpps
    container_name: hpfnm-migration-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=migration
      - POSTGRES_USER=migration
      - POSTGRES_DB=migration


networks:
  hmpps:
