version: "3"
services:
  localstack:
    image: localstack/localstack:1.3
    networks:
      - hmpps
    container_name: hpfnm-local-localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

  migration-db:
    image: postgres
    networks:
      - hmpps
    container_name: hpfnm-migration-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=migration
      - POSTGRES_USER=migration
      - POSTGRES_DB=migration


networks:
  hmpps:
