version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@9

parameters:
  alerts-slack-channel:
    type: string
    default: syscon-alerts-security
  releases-slack-channel:
    type: string
    default: dps-releases
  test-executor-packages:
    type: string
    default: "activities adjudications alerts appointments courtsentencing csip incidents locations sentencing visits"
  test-executors-count:
    type: integer
    default: 11

jobs:
  validate:
    executor:
      name: hmpps/java
      tag: "21.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check -x test
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}

  tests:
    parallelism: << pipeline.parameters.test-executors-count >>
    executor:
      name: hmpps/java_localstack_postgres
      jdk_tag: "21.0"
      localstack_tag: "3"
      postgres_tag: "16"
      postgres_username: "migration"
      postgres_password: "migration"
    steps:
      - checkout
      - hmpps/wait_till_ready
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: |
            set -x
            
            source .circleci/test_splitter_functions.sh

            cd src/test/kotlin || exit 1
            ROOT_PATH="uk/gov/justice/digital/hmpps/prisonerfromnomismigration"

            all_packages=$(find_all_packages "$ROOT_PATH")

            dedicated_executor_packages=()
            for i in << pipeline.parameters.test-executor-packages >>; do dedicated_executor_packages+=($i); done

            validate_number_of_executors "$CIRCLE_NODE_TOTAL" "${#dedicated_executor_packages[@]}"

            common_executor_packages=()
            for package in "${all_packages[@]}"; do
              if [[ ! " ${dedicated_executor_packages[*]} " =~ ${package} ]]; then
                common_executor_packages+=("$package")
              fi
            done
  
            index_output_file="test_classes$CIRCLE_NODE_INDEX.txt"
            > "$index_output_file"

            if [[ ! $(last_executor "$CIRCLE_NODE_INDEX" "$CIRCLE_NODE_TOTAL") ]]; then
              echo -e "Finding test classes for dedicated executor from package=${dedicated_executor_packages[$CIRCLE_NODE_INDEX]}\n"
              find_test_classes "$ROOT_PATH" "${dedicated_executor_packages[$CIRCLE_NODE_INDEX]}" "$index_output_file"
            else
              echo -e "Finding test classes for common executor from packages=${common_executor_packages[*]}\n"
              for common_executor_package in "${common_executor_packages[@]}"; do
                find_test_classes "$ROOT_PATH" "$common_executor_package" "$index_output_file"
              done
            fi

            echo -e "Executor $CIRCLE_NODE_INDEX will run tests for classes: $(cat "$index_output_file")\n"

            # Fail the build if no test files were found - unless we're in the bundled executor (which could potentially have zero tests)
            if [[ ! $(last_executor "$CIRCLE_NODE_INDEX" "$CIRCLE_NODE_TOTAL") ]]; then
              [ -s test_classes"$CIRCLE_NODE_INDEX".txt ] || circleci-agent step halt
            fi
      - run:
          command: |
            GRADLE_ARGS=$(cat src/test/kotlin/test_classes$CIRCLE_NODE_INDEX.txt \
            | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
            
            echo "Prepared arguments for Gradle: $GRADLE_ARGS"

            ./gradlew test $GRADLE_ARGS
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - tests:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_multiplatform_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - tests
            - build_docker
            - helm_lint
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          jira_update: true
          jira_env_type: staging
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context:
            - hmpps-common-vars
            - hmpps-prisoner-from-nomis-migration-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          jira_update: true
          jira_env_type: production
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          context:
            - hmpps-common-vars
            - hmpps-prisoner-from-nomis-migration-prod
          requires:
            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "29 8 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          cache_key: "v2_0"
          jdk_tag: "21.0"
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
  security-weekly:
    triggers:
      - schedule:
          cron: "53 8 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars


