name: combine-prs

on:
  schedule:
    - cron: "40 7 * * MON-FRI" # Every weekday at 07:10 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5
        with:
          branch_prefix: api-docs-
          pr_title: Combined update of api docs
          labels: combined-pr
