name: Run gradle checks with localstack and postgres instances
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: false
        default: '21'
      java-options:
        type: string
        default: ''
        required: false
      postgres-tag:
        type: string
        required: true
      postgres-password:
        type: string
        default: 'dev'
        required: false
      postgres-username:
        type: string
        default: 'root'
        required: true
      postgres-db:
        type: string
        default: 'postgres'
        required: false
      gradle-command:
        type: string
        default: './gradlew check'
        required: false
      localstack-services:
        type: string
        default: 'sqs,sns'
        required: false
      localstack-tag:
        type: string
        default: 'latest'
        required: false
      artifact-name:
        type: string
        default: 'test-results'
        required: false
      build-dir:
        type: string
        default: 'build'
        required: false
permissions:
  contents: read
jobs:
  gradle-localstack-postgres-verify:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:${{ inputs.postgres-tag }}
        env:
          POSTGRES_USER: ${{ inputs.postgres-username }}
          POSTGRES_PASSWORD: ${{ inputs.postgres-password }}
          POSTGRES_DB: ${{ inputs.postgres-db}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      localstack:
        image: localstack/localstack:${{ inputs.localstack-tag }}
        env:
          ES_PORT_EXTERNAL: 4571
          DOCKER_HOST: 'unix:///var/run/docker.sock'
          AWS_EXECUTION_ENV: True
          PERSISTENCE: 1
          SERVICES: "${{ inputs.localstack-services }}"
        options: >-
          --name localstack
          --health-cmd "curl -sS 127.0.0.1:4566 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 4566:4566
          - 4571:4571
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java-version }}'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run checks with gradle
        shell: bash
        run: |
          export JAVA_OPTS="${{ inputs.java-options }}"
          ${{ inputs.gradle-command }}
      - name: Upload the artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: |
            ${{ inputs.build-dir }}/test-results
            ${{ inputs.build-dir }}/reports/tests
      - name: publish test report
        if: ${{ !cancelled() }}
        uses: dorny/test-reporter@v2
        with:
          artifact: ${{ inputs.artifact-name }}
          name: Test Report
          path: 'test-results/**/*.xml'
          reporter: java-junit
          fail-on-error: false
